/* Snack Print — shared helpers (region-aware) */

const STAGE_KEYS = ["agriculture", "processing", "packaging", "transport", "retail"];

// Modelled regional transport factor (applies to the transport stage only)
const REGION_T = { EU: 1.0, US: 1.25, ASIA: 0.9 };
const REGIONS = ["EU", "US", "ASIA"];

function stageVal(snack, k, region) {
  const v = snack.stages[k] || 0;
  if (k === "transport" && region && REGION_T[region]) return v * REGION_T[region];
  return v;
}

function snackTotal(snack, region) {
  return STAGE_KEYS.reduce((s, k) => s + stageVal(snack, k, region), 0);
}

function dominantStage(snack, region) {
  let best = null, bestV = -1;
  for (const k of STAGE_KEYS) {
    const v = stageVal(snack, k, region);
    if (v > bestV) { bestV = v; best = k; }
  }
  return best;
}

// Lowest-footprint alternative in the same aisle (>=5% saving to qualify)
function bestSwap(snack, region) {
  const mine = snackTotal(snack, region);
  let best = null, bv = Infinity;
  SNACKS.forEach((o) => {
    if (o.cat === snack.cat && o.id !== snack.id) {
      const t = snackTotal(o, region);
      if (t < bv) { bv = t; best = o; }
    }
  });
  if (!best || bv >= mine * 0.95) return null;
  return { snack: best, pct: Math.round((1 - bv / mine) * 100) };
}

// unit: '100g' | 'serving' | 'yearly'.  freq = times per week (for yearly)
function unitFactor(snack, unit, freq) {
  if (unit === "100g") return 1;
  const perServing = snack.serving / 100;
  if (unit === "serving") return perServing;
  return perServing * (freq || 0) * 52; // yearly
}

function unitLabel(snack, unit, freq) {
  if (unit === "100g") return "per 100 g";
  if (unit === "serving") return "per serving (" + snack.serving + " g)";
  return "per year \u00b7 " + freq + "\u00d7/week";
}

// format kg CO2e nicely; small -> grams
function fmtCO2(kg) {
  if (kg < 0.001) return { num: "0", unit: "g CO\u2082e" };
  if (kg < 1) return { num: Math.round(kg * 1000).toLocaleString(), unit: "g CO\u2082e" };
  if (kg < 100) return { num: kg.toFixed(2), unit: "kg CO\u2082e" };
  return { num: Math.round(kg).toLocaleString(), unit: "kg CO\u2082e" };
}

function fmtNum(n, dp) {
  if (dp === undefined) dp = n < 1 ? 2 : n < 10 ? 1 : 0;
  return n.toLocaleString(undefined, { minimumFractionDigits: dp, maximumFractionDigits: dp });
}

// Default thumbnail URL per snack — pulled from window.SNACK_THUMBS, a
// hand-curated snack.id -> Wikipedia food-photo URL map populated by
// thumbs.js (generated by _fetch_thumbs.py). User drops still override.
function thumbUrl(snack) {
  return (window.SNACK_THUMBS && window.SNACK_THUMBS[snack.id]) || "";
}

// plain-text till receipt (for copy-to-clipboard)
function asciiReceipt(snack, unit, freq, region) {
  const W = 34;
  const pad = (l, r) => l + " ".repeat(Math.max(1, W - l.length - r.length)) + r;
  const center = (s) => " ".repeat(Math.max(0, Math.floor((W - s.length) / 2))) + s;
  const rule = (c) => c.repeat(W);
  const factor = unitFactor(snack, unit, freq);
  const total = snackTotal(snack, region) * factor;
  const dom = dominantStage(snack, region);
  const lines = [
    center("SNACK PRINT CO2 GROCER"),
    center("carbon till receipt"),
    rule("="),
    snack.name,
    pad(snack.sku, snack.cat),
    pad("BASIS", unitLabel(snack, unit, freq)),
    pad("REGION", region),
    rule("-"),
  ];
  STAGE_KEYS.forEach((k) => {
    const v = stageVal(snack, k, region) * factor;
    const f = fmtCO2(v);
    const share = stageVal(snack, k, region) / snackTotal(snack, region);
    const bar = "#".repeat(Math.max(1, Math.round(share * 12)));
    lines.push(pad((k === dom ? "*" : " ") + k.toUpperCase().slice(0, 11), f.num + " " + f.unit));
    lines.push("  " + bar + " " + Math.round(share * 100) + "%");
  });
  const f = fmtCO2(total);
  lines.push(rule("="));
  lines.push(pad("TOTAL", f.num + " " + f.unit));
  lines.push(pad("DOMINANT", "*" + dom.toUpperCase()));
  lines.push(rule("-"));
  lines.push(pad(fmtNum(total / EQUIV.car_km.perUnit), "km petrol car"));
  lines.push(pad(fmtNum(total / EQUIV.showers.perUnit), "hot showers"));
  lines.push(rule("-"));
  lines.push("Modelled estimate: Poore & Nemecek");
  lines.push("2018 x Open Food Facts categories.");
  lines.push(center("* thank you *"));
  return lines.join("\n");
}

Object.assign(window, {
  STAGE_KEYS, REGIONS, REGION_T, stageVal, snackTotal, dominantStage, bestSwap,
  unitFactor, unitLabel, fmtCO2, fmtNum, asciiReceipt, thumbUrl,
});
